[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip RP2040"

[build]
target = "aarch64-apple-darwin"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"
